fos_rest:
    param_fetcher_listener: true
    body_listener:          true
    format_listener:        true
    routing_loader:
        default_format: json
        include_format:       false
    view:
        view_response_listener: force
    body_converter:
        enabled: true
        validate: true
