version: '3'
services:
    php:
      build:
        context: docker/php-fpm
        args:
          TIMEZONE: ${TIMEZONE}
      ports:
        - '9002:9000'
      volumes:
        - ./:/var/www/symfony
        - ./docker/logs/symfony:/var/www/symfony/var/logs

    nginx:
      build: docker/nginx
      ports:
        - '80:80'
#      links:
#        - php
      volumes:
        - ./:/var/www/symfony
        - ./docker/logs/nginx/:/var/log/nginx