#index:
#    path: /
##    controller: App\Controller\DefaultController::index
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc

sonata_api_user:
    type:         rest
    prefix:       /api
    resource:     "../src/Controller"
